# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fulcrumdemoapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://github.com/iburizu/fulcrum/
        username: ${{ secrets.AzureAppService_ContainerUsername_35e61dacee4a488eb093e29c312db9ae }}
        password: ${{ secrets.AzureAppService_ContainerPassword_83f694e1720943f189fea2ca82e4d929 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: github.com/iburizu/fulcrum/${{ secrets.AzureAppService_ContainerUsername_35e61dacee4a488eb093e29c312db9ae }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fulcrumdemoapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_54de06c5fb484428874f9b18818df83c }}
        images: 'github.com/iburizu/fulcrum/${{ secrets.AzureAppService_ContainerUsername_35e61dacee4a488eb093e29c312db9ae }}/appsvc/staticsite:${{ github.sha }}'